using FluentAssertions;
using IdentityService.Domain.Entities;
using IdentityService.Domain.Enums;
using NUnit.Framework;

namespace IdentityService.Tests.Domain;

[TestFixture]
public class UserTests
{
    [Test]
    public void User_DefaultRole_IsCustomer()
    {
        var user = new User();
        user.Role.Should().Be(UserRole.Customer);
    }

    [Test]
    public void User_DefaultEmailVerified_IsFalse()
    {
        var user = new User();
        user.IsEmailVerified.Should().BeFalse();
    }

    [Test]
    public void User_DefaultIsActive_IsTrue()
    {
        var user = new User();
        user.IsActive.Should().BeTrue();
    }

    [Test]
    public void User_Id_IsAutoGenerated()
    {
        var user = new User();
        user.Id.Should().NotBe(Guid.Empty);
    }

    [Test]
    public void User_TwoInstances_HaveDifferentIds()
    {
        var user1 = new User();
        var user2 = new User();
        user1.Id.Should().NotBe(user2.Id);
    }

    [Test]
    public void User_CanAssignAdminRole()
    {
        var user = new User { Role = UserRole.Admin };
        user.Role.Should().Be("Admin");
    }

    [Test]
    public void User_CanAssignSellerRole()
    {
        var user = new User { Role = UserRole.Seller };
        user.Role.Should().Be("Seller");
    }

    [Test]
    public void User_PasswordHash_IsNotStoredAsPlaintext()
    {
        const string password = "MyPassword123";
        var hash = BCrypt.Net.BCrypt.HashPassword(password, workFactor: 4);

        var user = new User { PasswordHash = hash };
        user.PasswordHash.Should().NotBe(password);
        user.PasswordHash.Should().StartWith("$2");
    }

    [Test]
    public void OtpToken_DefaultIsUsed_IsFalse()
    {
        var otp = new OtpToken();
        otp.IsUsed.Should().BeFalse();
    }

    [Test]
    public void RefreshToken_DefaultIsRevoked_IsFalse()
    {
        var token = new RefreshToken();
        token.IsRevoked.Should().BeFalse();
    }

    [Test]
    public void User_OtpTokens_DefaultsToEmptyCollection()
    {
        var user = new User();
        user.OtpTokens.Should().NotBeNull().And.BeEmpty();
    }

    [Test]
    public void User_RefreshTokens_DefaultsToEmptyCollection()
    {
        var user = new User();
        user.RefreshTokens.Should().NotBeNull().And.BeEmpty();
    }
}
