using FluentAssertions;
using NUnit.Framework;
using ProductService.Domain.Entities;

namespace ProductService.Tests.Domain;

[TestFixture]
public class CategoryTests
{
    [Test]
    public void Category_Id_IsAutoGenerated()
    {
        var category = new Category();
        category.Id.Should().NotBe(Guid.Empty);
    }

    [Test]
    public void Category_TwoInstances_HaveDifferentIds()
    {
        var c1 = new Category();
        var c2 = new Category();
        c1.Id.Should().NotBe(c2.Id);
    }

    [Test]
    public void Category_DefaultIsActive_IsTrue()
    {
        var category = new Category();
        category.IsActive.Should().BeTrue();
    }

    [Test]
    public void Category_DefaultDisplayOrder_IsZero()
    {
        var category = new Category();
        category.DisplayOrder.Should().Be(0);
    }

    [Test]
    public void Category_DefaultParentCategoryId_IsNull()
    {
        var category = new Category();
        category.ParentCategoryId.Should().BeNull();
    }

    [Test]
    public void Category_DefaultImageUrl_IsNull()
    {
        var category = new Category();
        category.ImageUrl.Should().BeNull();
    }

    [Test]
    public void Category_SubCategories_DefaultsToEmptyList()
    {
        var category = new Category();
        category.SubCategories.Should().NotBeNull().And.BeEmpty();
    }

    [Test]
    public void Category_Products_DefaultsToEmptyList()
    {
        var category = new Category();
        category.Products.Should().NotBeNull().And.BeEmpty();
    }

    [Test]
    public void Category_CanHaveParentCategory()
    {
        var parent = new Category { Name = "Electronics" };
        var child = new Category
        {
            Name = "Phones",
            ParentCategoryId = parent.Id,
            ParentCategory = parent
        };
        child.ParentCategoryId.Should().Be(parent.Id);
        child.ParentCategory.Name.Should().Be("Electronics");
    }

    [Test]
    public void Category_CreatedAt_IsSetOnCreation()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var category = new Category();
        category.CreatedAt.Should().BeAfter(before);
    }
}
