using FluentAssertions;
using NUnit.Framework;
using ProductService.Domain.Entities;

namespace ProductService.Tests.Domain;

[TestFixture]
public class ProductTests
{
    [Test]
    public void Product_Id_IsAutoGenerated()
    {
        var product = new Product();
        product.Id.Should().NotBe(Guid.Empty);
    }

    [Test]
    public void Product_TwoInstances_HaveDifferentIds()
    {
        var p1 = new Product();
        var p2 = new Product();
        p1.Id.Should().NotBe(p2.Id);
    }

    [Test]
    public void Product_DefaultIsActive_IsTrue()
    {
        var product = new Product();
        product.IsActive.Should().BeTrue();
    }

    [Test]
    public void Product_DefaultIsFeatured_IsFalse()
    {
        var product = new Product();
        product.IsFeatured.Should().BeFalse();
    }

    [Test]
    public void Product_DefaultStockQuantity_IsZero()
    {
        var product = new Product();
        product.StockQuantity.Should().Be(0);
    }

    [Test]
    public void Product_DefaultDiscountPercent_IsZero()
    {
        var product = new Product();
        product.DiscountPercent.Should().Be(0);
    }

    [Test]
    public void Product_DefaultLowStockThreshold_IsTen()
    {
        var product = new Product();
        product.LowStockThreshold.Should().Be(10);
    }

    [Test]
    public void Product_DefaultAverageRating_IsZero()
    {
        var product = new Product();
        product.AverageRating.Should().Be(0);
    }

    [Test]
    public void Product_DefaultReviewCount_IsZero()
    {
        var product = new Product();
        product.ReviewCount.Should().Be(0);
    }

    [Test]
    public void Product_Images_DefaultsToEmptyList()
    {
        var product = new Product();
        product.Images.Should().NotBeNull().And.BeEmpty();
    }

    [Test]
    public void Product_Variants_DefaultsToEmptyList()
    {
        var product = new Product();
        product.Variants.Should().NotBeNull().And.BeEmpty();
    }

    [Test]
    public void Product_Specifications_DefaultsToEmptyList()
    {
        var product = new Product();
        product.Specifications.Should().NotBeNull().And.BeEmpty();
    }

    [Test]
    public void Product_IsLowStock_WhenStockBelowThreshold()
    {
        var product = new Product { StockQuantity = 5, LowStockThreshold = 10 };
        (product.StockQuantity < product.LowStockThreshold).Should().BeTrue();
    }

    [Test]
    public void Product_IsNotLowStock_WhenStockAboveThreshold()
    {
        var product = new Product { StockQuantity = 50, LowStockThreshold = 10 };
        (product.StockQuantity < product.LowStockThreshold).Should().BeFalse();
    }

    [Test]
    public void Product_DiscountedPrice_CanBeNull()
    {
        var product = new Product();
        product.DiscountedPrice.Should().BeNull();
    }

    [Test]
    public void Product_CreatedAt_IsSetOnCreation()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var product = new Product();
        product.CreatedAt.Should().BeAfter(before);
    }
}
