using FluentAssertions;
using NUnit.Framework;
using OrderService.Domain.Entities;

namespace OrderService.Tests.Domain;

[TestFixture]
public class CartTests
{
    [Test]
    public void CartItem_Id_IsAutoGenerated()
    {
        var item = new CartItem();
        item.Id.Should().NotBe(Guid.Empty);
    }

    [Test]
    public void CartItem_DefaultQuantity_IsOne()
    {
        var item = new CartItem();
        item.Quantity.Should().Be(1);
    }

    [Test]
    public void CartItem_SelectedVariant_DefaultsToNull()
    {
        var item = new CartItem();
        item.SelectedVariant.Should().BeNull();
    }

    [Test]
    public void CartItem_AddedAt_IsSetOnCreation()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var item = new CartItem();
        item.AddedAt.Should().BeAfter(before);
    }

    [Test]
    public void CartItem_TwoInstances_HaveDifferentIds()
    {
        var i1 = new CartItem();
        var i2 = new CartItem();
        i1.Id.Should().NotBe(i2.Id);
    }

    [Test]
    public void CartItem_LineTotal_IsQuantityTimesUnitPrice()
    {
        var item = new CartItem { UnitPrice = 250m, Quantity = 3 };
        var lineTotal = item.UnitPrice * item.Quantity;
        lineTotal.Should().Be(750m);
    }

    [Test]
    public void CartItem_CanExceedQuantityOne()
    {
        var item = new CartItem { Quantity = 5 };
        item.Quantity.Should().Be(5);
    }
}
