using FluentAssertions;
using NUnit.Framework;
using OrderService.Domain.Entities;

namespace OrderService.Tests.Domain;

[TestFixture]
public class OrderTests
{
    [Test]
    public void Order_Id_IsAutoGenerated()
    {
        var order = new Order();
        order.Id.Should().NotBe(Guid.Empty);
    }

    [Test]
    public void Order_TwoInstances_HaveDifferentIds()
    {
        var o1 = new Order();
        var o2 = new Order();
        o1.Id.Should().NotBe(o2.Id);
    }

    [Test]
    public void Order_DefaultStatus_IsPlaced()
    {
        var order = new Order();
        order.Status.Should().Be(OrderStatus.Placed);
    }

    [Test]
    public void Order_DefaultPaymentStatus_IsPending()
    {
        var order = new Order();
        order.PaymentStatus.Should().Be(PaymentStatus.Pending);
    }

    [Test]
    public void Order_DefaultDiscountAmount_IsZero()
    {
        var order = new Order();
        order.DiscountAmount.Should().Be(0);
    }

    [Test]
    public void Order_DefaultDeliveryCharge_IsZero()
    {
        var order = new Order();
        order.DeliveryCharge.Should().Be(0);
    }

    [Test]
    public void Order_DefaultIsFraudFlagged_IsFalse()
    {
        var order = new Order();
        order.IsFraudFlagged.Should().BeFalse();
    }

    [Test]
    public void Order_Items_DefaultsToEmptyList()
    {
        var order = new Order();
        order.Items.Should().NotBeNull().And.BeEmpty();
    }

    [Test]
    public void Order_StatusHistory_DefaultsToEmptyList()
    {
        var order = new Order();
        order.StatusHistory.Should().NotBeNull().And.BeEmpty();
    }

    [Test]
    public void Order_TotalAmount_ReflectsAssignedValue()
    {
        var order = new Order
        {
            SubTotal = 1000m,
            DiscountAmount = 100m,
            DeliveryCharge = 50m,
            TotalAmount = 950m
        };
        order.TotalAmount.Should().Be(950m);
    }

    [Test]
    public void Order_CreatedAt_IsSetOnCreation()
    {
        var before = DateTime.UtcNow.AddSeconds(-1);
        var order = new Order();
        order.CreatedAt.Should().BeAfter(before);
    }

    [Test]
    public void Order_CouponCode_DefaultsToNull()
    {
        var order = new Order();
        order.CouponCode.Should().BeNull();
    }

    [Test]
    public void Order_DeliveredAt_DefaultsToNull()
    {
        var order = new Order();
        order.DeliveredAt.Should().BeNull();
    }
}
